name: Update Code Stats

on:
  schedule:
    - cron: '0 0 */4 * *' # Runs at 00:00 every 4 days
  workflow_dispatch: # Allows you to manually trigger the script from the GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Scraper
        working-directory: ./backend
        run: node multi-scrape-server.js
